# example config

logFile: ""
logVerbose: true

profiles:
  home:
    srcHost: vm
    dstHost: rasp
    sessionKey: HcicQW1mAwAsrR/V2zq8/H/fVc0wxLiTshCWm3rFoCw=

ethers:
  2a01:aaaa:aaaa:aaaa::1: 42:42:42:42:42:42
  2a01:aaaa:aaaa:aaaa::2: 42:42:42:42:42:43

hostnames:
  rasp: 2a01:aaaa:aaaa:aaaa::1/64
  vm: 2a01:aaaa:aaaa:aaaa::2/64

internalNic: tun42
rotationTime: 10
externalNic: enp0s3
addressLifetime: 12
encryption: false

# unused for now
hashAlgorithm: sha256
cryptAlgorithm: aes256
regenInterval: 1000
regenWindow: 500
firewall: true
randSource: ""
